# Generated by Django 3.0.7 on 2020-06-12 15:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20200612_1520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='D',
            new_name='Profile',
        ),
    ]
